# Sample Kubernetes secrets for testing secrets-snitcher.
# These are dummy values -- do not use real credentials.
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  # username: admin
  username: YWRtaW4=
  # password: hunter2
  password: aHVudGVyMg==
---
apiVersion: v1
kind: Secret
metadata:
  name: api-key
  namespace: default
type: Opaque
data:
  # key: sk-fake-1234567890abcdef
  key: c2stZmFrZS0xMjM0NTY3ODkwYWJjZGVm
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-cert
  namespace: default
type: kubernetes.io/tls
data:
  # Self-signed dummy values (not real certs)
  tls.crt: LS0tLS1CRUdJTi0tLS0tCmR1bW15LWNlcnQtZm9yLXRlc3RpbmcKLS0tLS1FTkQtLS0tLQ==
  tls.key: LS0tLS1CRUdJTi0tLS0tCmR1bW15LWtleS1mb3ItdGVzdGluZwotLS0tLUVORC0tLS0t
